access files from local resource

In [35]:
import os

pwd = os.getcwd()
pwd

'/Users/dickinsd/Github/ds-bootcamp-unn'

if you wanted to change the directory:

import os
os.chdir('/path-to-data')

In [3]:
x = 2
y = 3
z = 'kl7010'

x*y

6

In [4]:
[1, 2, 3]

[1, 2, 3]

In [6]:
# a list = vector in R

vector1 = [1,2,3]

type(vector1), len(vector1)

(list, 3)

In [7]:
print(vector1[2])

3


In [9]:
# creating advanced multidimensional lists

import numpy as np 

vector1 = np.array([1,2,3])
print(vector1, type(vector1))

[1 2 3] <class 'numpy.ndarray'>


In [12]:
# let's sort the list

vector2 = np.array([3,4,2,1,6,9])
vector2.sort()
vector2

array([1, 2, 3, 4, 6, 9])

data frame = tabular structure

fundamental form of data store in python

In [31]:
A = [5, 10, 15]
B = ['david', 'zain', 'nick']
C = [True, True, False]

dataframe1 = np.array([A,B,C])
print(dataframe1)

[['5' '10' '15']
 ['david' 'zain' 'nick']
 ['True' 'True' 'False']]


In [21]:
# to access just one row: 

print(dataframe1[0])

['5' '10' '15']


make the data frame bigger

In [32]:
print(dataframe1)

[['5' '10' '15']
 ['david' 'zain' 'nick']
 ['True' 'True' 'False']]


In [33]:
D = [20, 30, 40]

dataframe1 = np.vstack([dataframe1,D])
print(dataframe1)

[['5' '10' '15']
 ['david' 'zain' 'nick']
 ['True' 'True' 'False']
 ['20' '30' '40']]


performing numerical computations of rows that are not already integers...

In [24]:
dataframe1[0].astype(int) + dataframe1[3].astype(int)

array([25, 40, 55])

In [26]:
dataframe1[0].astype(int) *2

array([10, 20, 30])

removing rows

In [34]:
dataframe1 = np.delete(dataframe1,2,0)
print(dataframe1)

[['5' '10' '15']
 ['david' 'zain' 'nick']
 ['20' '30' '40']]
